name: dependency-updater

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  push:
    branches:
    - dependency-updater
      
jobs:
  update-latest-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: ['ytt', 'kapp', 'kbld', 'imgpkg', 'vendir']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Current Release Version
        id: current-version
        run: |
          set -eou pipefail
          echo ::set-output name=version::$(yq eval '.${{ matrix.tool }}_version' ./hack/dependencies.yml) 
      - name: Get Latest Release Version
        id: latest-version
        run: |
          set -eou pipefail
          echo ::set-output name=version::$(curl -sL https://api.github.com/repos/vmware-tanzu/carvel-${{ matrix.tool }}/releases/latest | jq -r '.tag_name')
      - name: Update Dependencies File
        if: ${{ steps.current-version.outputs.version }} != ${{ steps.latest-version.outputs.version }}
        run: |
          set -eou pipefail
          
          old_darwin_amd64_sha=$(yq eval '.${{ matrix.tool }}_checksum_darwin' ./hack/dependencies.yml) 
          old_linux_amd64_sha=$(yq eval '.${{ matrix.tool }}_checksum_linux' ./hack/dependencies.yml)
          
          release_notes=$(curl https://api.github.com/repos/vmware-tanzu/carvel-${{ matrix.tool }}/releases/latest | jq .body -r)
          new_darwin_amd64_sha=$( echo "$release_notes" | grep ${{ matrix.tool }}-darwin-amd64 | awk '{print $1;}')
          new_linux_amd64_sha=$( echo "$release_notes" | grep ${{ matrix.tool }}-linux-amd64 | awk '{print $1;}')
                    
          yq eval '.${{ matrix.tool }}_version = "${{ steps.latest-version.outputs.version }}"' -i ./hack/dependencies.yml
          yq eval ".${{ matrix.tool }}_checksum_darwin = \"${new_darwin_amd64_sha}\"" -i ./hack/dependencies.yml
          yq eval ".${{ matrix.tool }}_checksum_linux = \"${new_linux_amd64_sha}\"" -i ./hack/dependencies.yml          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump ${{ matrix.tool }} to ${{ steps.latest-version.outputs.version }}
          title: Bump ${{ matrix.tool }} to ${{ steps.latest-version.outputs.version }}
          delete-branch: true
          body: |
            Auto-generated by https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          base: develop
          branch: bump-${{ matrix.tool }}-${{ steps.latest-version.outputs.version }}
          
         
