name: Trivy CVE Dependency Scanner

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
    - enable-trivy-scan
  workflow_dispatch:
  
jobs:
  scan-all:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go 1.x
        uses: actions/setup-go@v1
        with:
          go-version: "1.17"
      - name: Build the kapp-controller artifacts
        id: build
        run: |
          ./hack/install-deps.sh
          ./hack/build.sh

          # docker image
          docker build -t docker.io/carvel/kapp-controller:${{ github.sha }} .
          
          # Get the latest released docker image sha
          curl -sL https://api.github.com/repos/vmware-tanzu/carvel-kapp-controller/releases/latest | jq -r '.assets[].browser_download_url' | wget -i -

          echo ::set-output name=image::$(yq eval '.spec.template.spec.containers[0].image' release.yml -N -j | jq 'select(. != null)' -r)
      - name: Install Trivy
        run: |
          brew install aquasecurity/trivy/trivy

          # download the sarif format template
          git clone --depth 1 https://github.com/aquasecurity/trivy
      - name: Run Trivy Reports
        run: |
          export TRIVY_IGNORE_UNFIXED=true
          export TRIVY_SEVERITY="MEDIUM,HIGH,CRITICAL"
          export TRIVY_TEMPLATE="@trivy/contrib/sarif.tpl"

          # kapp-controller binary - output in sarif and json
          trivy rootfs --format template --output trivy-results-binary.sarif "controller"
          trivy rootfs --format json --output trivy-results-binary.json "controller"

          # kapp-controller docker image - output in sarif and json
          trivy image --format template --output trivy-results-image.sarif "docker.io/carvel/kapp-controller:${{ github.sha }}"
          trivy image --format json --output trivy-results-image.json "docker.io/carvel/kapp-controller:${{ github.sha }}"
          
          # latest released kapp-controller docker image - output in sarif and json
          trivy image --format template --output trivy-results-image-latest.sarif ${{ steps.build.outputs.image }})
          trivy image --format json --output trivy-results-image-latest.json ${{ steps.build.outputs.image }})
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: '.'
      - name: Check for new Vulnerabilities
        run: |
          set -o pipefail

          summary="Trivy scan has found new vulnerabilities - check https://github.com/vmware-tanzu/carvel-kapp-controller/security/code-scanning for more"

          vulnCountBinary=$(jq '[ .Results[].Vulnerabilities ] | length' trivy-results-binary.json)
          vulnCountImage=$(jq '[ .Results[].Vulnerabilities ] | length' trivy-results-image.json)
          vulnCountImageLatest=$(jq '[ .Results[].Vulnerabilities ] | length' trivy-results-image-latest.json)
          if [ $vulnCountImage -eq 0 && $vulnCountBinary -eq 0 && $vulnCountImageLatest -eq 0]; then
            summary="Trivy Scan has not found any new Security Issues"
          fi

          echo "SUMMARY=$summary" >> $GITHUB_ENV
      - name: Send Slack Notification
        if: success()
        uses: slackapi/slack-github-action@v1.15.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: C02MTA7F2G1
          slack-message: "${{ env.SUMMARY }}"
      - name: Send Failure notification
        if: failure()
        uses: slackapi/slack-github-action@v1.15.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: C02MTA7F2G1
          slack-message: "Trivy scan workflow failed. Please check the latest github action run for trivy scanner."
