name: Trivy CVE Dependency Scanner

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan-latest-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Docker Image Sha
        id: latest-sha
        run: |
          set -eox pipefail
          # Get the latest released docker image sha
          curl -sL https://api.github.com/repos/vmware-tanzu/carvel-kapp-controller/releases/latest | jq -r '.assets[] | select(.name | contains("release.yml")).browser_download_url' | wget -i -

          echo "image=$(yq eval '.spec.template.spec.containers[0].image' release.yml -N -oj | jq 'select(. != null)' -r)"  >> $GITHUB_OUTPUT
          echo "{tag}={$(curl -sL https://api.github.com/repos/vmware-tanzu/carvel-kapp-controller/releases/latest | jq -r '.tag_name')}" >> $GITHUB_OUTPUT
      - name: Run Trivy
        run: |
          echo ${{join(steps.latest-sha.outputs.*, '\n')}}
